### ISSUE TITLE
NTFY credentials

### ISSUE THREAD

**Issue by Proximus888** [2boom-ua/dockcheck#1]
I selfhost NTFY.sh, is there a way to pass on credentials (user+password) in the json?

**Comment by 2boom-ua** [comment]
Hi, 
"NTFY": {
		"ON": true,
		"SUB": "subscribe_topick_name",
		"WEB": "https://your_nttfy_server_address"
	},
no more need

**Comment by Proximus888** [comment]
> Hi, 
> "NTFY": {
> 		"ON": true,
> 		"SUB": "subscribe_topick_name",
> 		"WEB": "https://your_nttfy_server_address"
> 	},
> no more need 

Well yes more is needed. 

NTFY has a authentication feature that only authenticated users can post. Enabled with 'auth-default-access: "deny-all"' in config.

The current setup only allows the user to post on open (not secured) topics. Topics open to the public.

**Comment by 2boom-ua** [comment]
> So now you can only post to open (not secured) topics, visible to anyone.

your ntfy server have your account with login and password) it only for you messages))

go https://your_nttfy_server_address
login with password
+Subscribe topic
generate topic name
then service will send to this Subscribe topic

**Comment by 2boom-ua** [comment]
I think better use external Ntfy server

**Comment by Proximus888** [comment]
> > So now you can only post to open (not secured) topics, visible to anyone.
> 
> your ntfy server have your account with login and password) it only for you messages))
> 
> go https://your_nttfy_server_address
> login with password

Only authenticated users can post new messages on topics.

Got around it with passing credentials through the url:  ' https://user:password@domain.tld'.

But I would prefer a seperate json 'user' and 'password' field.

**Comment by 2boom-ua** [comment]
Hm, anyone can send) but anyone can't read))
for send alert no need any login and password
